[project]
name = "functional"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hypothesis>=6.137.3",
    "pytest>=8.4.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
